# %YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/camera_d435i/imu"
#imu_topic: "/JA01/imu_3dm/data_raw"
image0_topic: "/camera_d435i/infra1/image"
image1_topic: "/camera_d435i/infra2/image"
output_path: "home/swarm/catkin_ws/src/VINS-Fusion/config/realsense_d435i/output"

cam0_calib: "infra1_kalibr_2.24.yaml"
cam1_calib: "infra2_kalibr_2.24.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

# Pinhole-radtan Kalibr extrinsics
body_T_cam0: !!opencv-matrix
        rows: 4
        cols: 4
        dt: d
        data: [ 0.99996757, -0.00605195, -0.00531381, -0.00351128,
                0.00604322,  0.99998037, -0.00165699, -0.00431916,
                0.00532373,  0.00162482,  0.99998451,  0.02001816, 
                0.,          0.,          0.,          1.         ]

body_T_cam1: !!opencv-matrix
        rows: 4
        cols: 4
        dt: d
        data: [ 0.99985473, -0.00626111, -0.015853,    0.04539504,
                0.00623295,  0.99997891, -0.00182508, -0.00406653,
                0.01586409,  0.00172601,  0.99987267,  0.01996696,
                0.,          0.,          0.,          1.         ]

# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ -5.7586305857286746e-03, -4.0463318787729019e-03,
#        9.9997523237933461e-01, 2.0329267950355900e-02,
#        -9.9998287214160420e-01, -1.0224590553211677e-03,
#        -5.7628118925283633e-03, 7.9325209639615653e-03,
#        1.0457519809151661e-03, -9.9999129084997906e-01,
#        -4.0403746097850135e-03, 2.8559824645148020e-03, 0., 0., 0., 1. ]

# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ -1.0021770212322867e-03, 3.6313480322730518e-04,
#        9.9999943188700535e-01, 1.5285779565991807e-02,
#        -9.9999216342926500e-01, -3.8303422615924010e-03,
#        -1.0007788055728661e-03, -5.2435791444330505e-02,
#        3.8299766679101843e-03, -9.9999259827824449e-01,
#        3.6697063849344680e-04, 8.6931302450199057e-03, 0., 0., 0., 1. ]


# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 0, 0, 1, 0.010,
#           -1, 0, 0, 0,
#            0, -1, 0, 0, 0., 0., 0., 1. ]

# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [ 0, 0, 1, -0.040,
#           -1, 0, 0, 0,
#            0, -1, 0, 0, 0., 0., 0., 1. ]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)


# acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
# gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
# acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.002
# gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
# g_norm: 9.805         # gravity magnitude


acc_n: 2.5859568880463858e-02          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 3.2408790141249294e-03         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 7.1765713730075628e-04         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 4.4384693741081766e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude


#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.00                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/swarm/catkin_ws/src/VINS-Fusion/config/realsense_d435i/output" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 4